### ISSUE TITLE
Better code rendering on mobile devices

### ISSUE THREAD

**Issue by ploeh** [ploeh/ploeh.github.com#226]
I've noticed that when viewed on my Android phone (with Chrome for Android), recent posts have suboptimal code listings. While code snippets are rendered with appropriate colours, they aren't rendered in a monospaced font.

As far as I can tell, the last one that looked good on my phone was [REST efficiency](http://blog.ploeh.dk/2014/01/20/rest-efficiency):

![screenshot_2016-02-23-17-22-57](https://cloud.githubusercontent.com/assets/242165/13258230/a1b04d9c-da52-11e5-8703-7d743cec4cb0.png)

The next article that shows code is [How to use FSharp.Core 4.3.0 when all you have is 4.3.1](http://blog.ploeh.dk/2014/01/30/how-to-use-fsharpcore-430-when-all-you-have-is-431):

![screenshot_2016-02-23-17-24-26](https://cloud.githubusercontent.com/assets/242165/13258277/d44144f0-da52-11e5-8d8c-81b5b2e364bc.png)

Both articles look fine (that is, code fonts are monospaced) on my laptop when viewed in Chrome.

My theory is that this change is cause by my shift from _CopySourceAsHTML_ (which doesn't work with modern versions of Visual Studio) to Visual Studio Power Tools.

**Comment by mariusschulz** [comment]
The problem is that *CopySourceAsHTML* creates HTML snippets like the following:

```html
<pre style="font-family:Consolas;font-size:13;color:black;">
    <!-- omitted for brevity -->
</pre>
```

As you can see, the CSS `font-family` property is set to `Consolas` without any fallback font. (At least, `monospace` should appear at the end.) That way, the default font (e.g. Times New Roman or Roboto) kicks in on systems that don't have Consolas installed.

I'd suggest one of the following two fixes, preferably the first one:

- Automatically (or manually) remove the entire `style` attribute from the `<pre>` tag and let your CSS do the rest.
- Override the `font-family` property of all `<pre>` tags in your CSS with `!important`, as in `font-family: Consolas, Menlo, Monaco, monospace !important;`

**Comment by ploeh** [comment]
@mariusschulz, thank you for the suggestion. As an experiment, I've removed the `style` attribute from my latest entry: http://blog.ploeh.dk/2016/10/25/when-variable-names-are-in-the-way

I think it looks correct on my Android device, and I can't tell the difference on my Windows machine. Did it help on Mac?

**Comment by mariusschulz** [comment]
@ploeh I currently can't double-check on my Mac, but your most recent post looks a lot better on my iPhone than previous ones. Now, code snippets are rendered in a proper monospaced font.

**Comment by ploeh** [comment]
I've removed the `style` tags from all posts now, and the code looks fine on my phone (and laptop, still).

I _think_ this is done now, so I'm going to close the issue.
