### ISSUE TITLE
Type parameters reversed

### ISSUE THREAD

**Issue by bender2k14** [ploeh/ploeh.github.com#456]
On [this line](https://github.com/ploeh/ploeh.github.com/blob/master/_posts/2019-02-25-an-example-of-interaction-based-testing-in-c.html#L189), I think the type parameter names in `IResult<S, E>` are in the opposite order than how you described them:
> `Right` is equivalent to `SuccessResult`, and `Left` corresponds to `ErrorResult`.

**Comment by ploeh** [comment]
Yes, they're reversed. No, this is (unfortunately) not an error.

Languages (OCaml, F#) that call the type _Result_ put the `OK` or `Success` case first (i.e. to the left) and the `Error` case second (i.e. to the right).

Languages (like Haskell) that call the type _Either_ put the `Left` case first (because, well, that's to the left) and the `Right` case second (to the right). Inherently, `Left` and `Right` carry no additional semantics, but by convention (or, by pun), `Right` is used for those results that are... well, _right_ (i.e. _correct_), which leaves the `Left` case for errors.

I usually follow that convention for both schools, which do, however, have the unfortunate power to confuse the careful reader.

FWIW, I usually favour the _Either_ terminology, but there was a reason I adopted the _Result_ terminology in the video. This is more evident if you watch the video, but basically, it's because I could explain how to arrive at the type gradually, via a series of refactorings from more specific Church-encoded types.

**Comment by bender2k14** [comment]
Oh, no!  Thanks for the clarification :)
