### ISSUE TITLE
Old/broken link to Skills Matter

### ISSUE THREAD

**Issue by bender2k14** [ploeh/ploeh.github.com#546]
The link https://skillsmatter.com/skillscasts/2323-bobs-last-language with the link text
> Robert C. Martin told us that years ago

in the post [Less is more: language features](https://blog.ploeh.dk/2015/04/13/less-is-more-language-features/) is broken because Skills Matter seems to be going out of business.

The link could be replaced with [this Wayback Machine link](https://web.archive.org/web/20191105135821/https://skillsmatter.com/skillscasts/2323-bobs-last-language).

I could make a PR with this change if you would like.

**Comment by ploeh** [comment]
Well, when you have a blog that spans decades, links are going to break.

You can navigate to that Wayback Machine link, but the video doesn't play there. This is a common problem with the Internet Archive. Links usually don't work. If you're technical, you can often work around that, but I don't wish to support any issues related to such things, since they're out of my control.

So I prefer letting stale links remain stale, unless a new authoritative home is found for a resource. For example, if someone manages to rescue all the videos from Skills Matter and find a new home for them, I'll happily link there instead.

**Comment by bender2k14** [comment]
Sure.  Refusing to fight link rot is a very reasonable position.  I had intended to suggest that at the end of my comment, but forgot to do so.

FWIW, the [Skills Matter's Vimeo account](https://vimeo.com/skillsmatter) still exists but the video in question isn't listed there.  It seems [the video](https://player.vimeo.com/video/26390541) is still available within Vimeo, but its privacy settings prevent it from being played anywhere.

**Comment by bender2k14** [comment]
The Skills Matter page linked to in your post (according to the Wayback Machine) doesn't seem to contain much beyond the video.  The video is a talk my Robert Martin and is titled "The Last Programming Language", and he has given that talk more than once ([Google search](https://www.google.com/search?q=The+Last+Programming+Language+robert+martin)).  Maybe one of those talks contains the same point that you are trying to cite.

**Comment by ploeh** [comment]
They probably do.

In order to figure that out, I'd have to watch the candidate video. I'm not convinced that that's the best use of my time, and I'm not particularly inclined to do it for the entertainment...

**Comment by bender2k14** [comment]
I agree.  Just wanted to throw all these suggestions out there in case you were interested.
