### ISSUE TITLE
[Suggestion] GitHub comments in place of Pull Requests

### ISSUE THREAD

**Issue by andresmoschini** [ploeh/ploeh.github.com#661]
I just found a blog that takes advantage of GitHub comments, maybe you are interested in something like this in place of the PRs: https://github.com/RehanSaeed/rehansaeed.github.io/issues/196

**Comment by ploeh** [comment]
Hi, thank you for writing. There are various systems out there that use GitHub issues for comments for static web sites. This one looks like it uses one of them.

There are various reasons I just include comments as part of a page's text. One has to do with some technical limitations of Jekyll, but another, more fundamental reason is decoupling. I could have embedded a Disqus discussion in each page, but that would mean, then, that I'd basically be tied to Disqus forever. What would happen if Disqus disappears or changes its terms of service?

Granted, I trust GitHub more than I trust Disqus, but doesn't that sort of system have the same dependency on a third-party system?

I'm actually not so paranoid that I believe that GitHub might deliberately try to lure me into using the platform more, just to spring some evil trap in the future. What does worry me, though, is having to depend on a system that actually isn't designed for the purpose of managing blog comments. What happens if GitHub changes its API in a way that breaks that system?

What happens if the maintainer of the integration system that enables this has left the building?

I can understand why some people choose this system, but I don't think it fits my requirements. I've been blogging for more than a decade; people link to my articles - even some of the old ones. It's an important part of my web presence that things are as stable as possible.

It's been [seven years since I last changed the underlying platform of the blog](https://blog.ploeh.dk/2013/03/03/moving-the-blog-to-jekyll). When you have hundreds of articles to migrate, that's a serious undertaking.

Jekyll is now getting long in the tooth, and I foresee the day when I'll again have to migrate the blog to a new technical platform. In that light, I'm actually quite happy that I chose to keep things as simple as they are.

**Comment by andresmoschini** [comment]
Makes sense, thanks for your answer!

**Comment by TysonMN** [comment]
This suggestion is very similar to #618.
