### ISSUE TITLE
[Translation] a post translation

### ISSUE THREAD

**Issue by RiceBen** [ploeh/ploeh.github.com#758]
Hi, Mark
I recently read your post about [tips for pull requests](https://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/), which helps me a lot. Thanks for the great article.

I would like to translate the post to Traditional Chinese and post it to [my personal blog](https://riceben.gitlab.io/). May I translate the post and post it? Then, of course, I'll clear to the reader that the author is you and shows the original post link. :)

**Comment by ploeh** [comment]
Thank you for writing. I'm happy that you like the article enough to want to translate it.

I seem to recall that someone already translated the article to Chinese some years ago, but I don't know if that page is still around. I also don't know how to search for it.

In either case, you're welcome to translate the article. I'd appreciate if you clearly indicate that I'm the original author, and that you link to my article, just as you suggested.

**Comment by RiceBen** [comment]
Hi, Mark
I've done the translation work. Very appreciate your help again.
Here is the [result](https://riceben.gitlab.io/posts/2021/tips-for-pr/).

**Comment by ploeh** [comment]
Looking good. I wonder if you could help me out with something related? My book _Dependency Injection Principles, Practices, and Patterns_ was sold for translation into Chinese, but I've no idea if it was ever published. It's difficult for me to investigate, since I don't know what the title would be in Chinese, or even how to type the title.

Could you do a web search and see if the book is published? I'm mostly just curious.

**Comment by RiceBen** [comment]
Hi, Mark
My pleasure.
I found the book already published on 30/7/2020.
The Chinese version can buy [here](https://www.tenlong.com.tw/products/9789864344987?list_name=srh)

Original Title: Dependency Injection: Principles, Practices, Patterns
Chinese Title: 依賴注入：原理、實作與設計模式

**Comment by ploeh** [comment]
Thank you, that's very helpful.
